######################################################################
# Automatically generated by qmake (2.01a) ? 6? 8 16:00:42 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += test.cpp
