######################################################################
# Automatically generated by qmake (2.01a) ? 8? 30 13:35:46 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += find.cpp
